# Generated by Django 6.1 on 2026-08-23 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cargo', models.CharField(choices=[('est', 'Estagiário'), ('jun', 'Júnior'), ('pln', 'Pleno'), ('sen', 'Sênior'), ('ger', 'Gerente')], default='jun', max_length=3)),
                ('salario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('horas_semana', models.PositiveIntegerField(default=40)),
                ('data_contratacao', models.DateField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionarios', to='core.departamento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='funcionario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name', 'user__last_name'],
                'permissions': [('can_manage_funcionarios', 'Pode gerenciar funcionários'), ('can_view_all_registros', 'Pode ver todos os registros de ponto')],
            },
        ),
        migrations.CreateModel(
            name='RegistroPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.DateField(auto_now_add=True)),
                ('horas_trabalhadas', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('observacao', models.TextField(blank=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='core.funcionario')),
            ],
            options={
                'ordering': ['-data'],
                'unique_together': {('funcionario', 'data')},
            },
        ),
    ]
