# Generated by Django 6.1 on 2026-08-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registroponto',
            options={'ordering': ['-data', '-entrada']},
        ),
        migrations.RemoveField(
            model_name='registroponto',
            name='horas_trabalhadas',
        ),
        migrations.AddField(
            model_name='registroponto',
            name='entrada',
            field=models.DateTimeField(default='2026-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registroponto',
            name='saida',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registroponto',
            name='data',
            field=models.DateField(),
        ),
    ]
